CREATE TABLE IF NOT EXISTS `users` (
    `uid` VARCHAR(128) NOT NULL COMMENT '用户id',
    `github_id` VARCHAR(128) NOT NULL COMMENT 'github用户id',
    `cred` VARCHAR(32) NOT NULL COMMENT 'ADMIN/USER/GUEST',
    `nickname` VARCHAR(128) NOT NULL COMMENT '用户名',
    `avatar` VARCHAR(128) NOT NULL COMMENT '用户头像',
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`uid`),
    INDEX `github_idx` (`github_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
